courses/urls.py
from django.urls import path
from .views import *

app_name = "courses"

urlpatterns = [
    path("all", All.as_view(), name="all"),
    path("all/manage", AllAdmin.as_view(), name="all_manage"),
    path("<int:id>/view", CourseView.as_view(), name="course_view"),
    path("<int:id>/edit", Edit.as_view(), name="edit"),
    path("<int:id>/delete", Delete.as_view(), name="delete"),
    path("<int:id>/submit/<str:code>", Submit.as_view(), name="submit")
]

main/urls.py
from django.urls import path
from .views import Home


app_name = "main"

urlpatterns = [
    path("", Home.as_view(), name="home")
]

pattendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", "main")),
    path('users/', include("users.urls", "users")),
    path('courses/', include("courses.urls", "courses"))
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("google/landing", GoogleLanding.as_view(), name="google_landing"),
    path("google/callback", GoogleCallback.as_view(), name="google_callback")
]

templates/pages/course_edit.html
{% extends "layouts/app.html" %}
{% load stringformat static admin_urls %}
{% block content_inner %}
    <div class="qrcode" style="display: none">
        <button>Close</button>
        <div class="inner">
            <h1>Refreshes in xx seconds</h1>
        </div>
    </div>
    <div class="course-edit">
        <form class="left" method="post">
            {% csrf_token %}
            <div class="item">
                <h1>Title:</h1>
                <input name="title" type="text" value="{{ course.title }}">
            </div>
            <div class="timepart item">
                <h1>Time:</h1>
                <div class="time">
                    <div class="start">
                        <input name="start_time" type="datetime-local"
                               value="{{ course.start_time|stringformat:'%Y-%m-%dT%H:%M' }}">
                    </div>
                    <h2>to</h2>
                    <div class="end">
                        <input name="end_time" type="datetime-local"
                               value="{{ course.end_time|stringformat:'%Y-%m-%dT%H:%M' }}">
                    </div>
                </div>
            </div>
            <div class="bottom">
                <input type="submit" value="Save">
                <button type="button" class="delete">Delete</button>
                <button type="button" class="qrcode">QR code</button>
                <a href="{% url course_opts|admin_urlname:'change' course.id %}" target="_blank">Advance edit</a>
                <a href="{% url attendance_opts|admin_urlname:'changelist' %}" target="_blank">Attendance details</a>
            </div>
        </form>
        <div class="right">
            <div class="present">
                <h1>Present</h1>
                <div class="users">
                    {% if attendance|length == 0 %}
                        <h2>Nobody is present :(</h2>
                    {% endif %}
                    {% for user in attendance %}
                        <div class="user">
                            <div class="left"><img src="




                                    {% if user.avatar %}{{ user.avatar }}{% else %}{% static 'images/guest.jpg' %}{% endif %}"
                                                   alt="">
                            </div>
                            <div class="right">
                                <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                                <h3>{{ user.email }}</h3>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="absent">
                <h1>Absent</h1>
                <div class="users">
                    {% if associated_users|length == 0 %}
                        <h2>Nobody is absent today!</h2>
                    {% endif %}
                    {% for user in associated_users %}
                        {% if not user in attendance %}
                            <div class="user">
                                <div class="left"><img src="




                                        {% if user.avatar %}{{ user.avatar }}{% else %}{% static 'images/guest.jpg' %}{% endif %}"
                                                       alt=""></div>
                                <div class="right">
                                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                                    <h3>{{ user.email }}</h3>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <form id="delete" style="display: none;" action="{% url 'courses:delete' course.id %}" method="POST">
        {% csrf_token %}
    </form>
{% endblock %}

{% block custom_javascript %}
    <script>
        let interval = null;
        isQRcode = localStorage.getItem("qrcode");
        if (isQRcode == "true") {
            let secondsPassed = 0;
            const secondsLimit = 10;
            document.querySelector("div.qrcode h1").innerHTML = `Refreshes in ${secondsLimit - secondsPassed} seconds`;
            document.querySelector("div.qrcode").style.display = "flex";

            interval = setInterval(() => {
                secondsPassed++;
                if (secondsPassed >= secondsLimit) {
                    window.location.reload()
                } else {
                    document.querySelector("div.qrcode h1").innerHTML = `Refreshes in ${secondsLimit - secondsPassed} seconds`;
                }
            }, 1000);
        }
        deleteButton = document.querySelector(".delete");
        deleteButton.addEventListener("click", (e) => {
            document.getElementById("delete").submit()
        });

        qrcodeButton = document.querySelector("button.qrcode");
        qrcodeButton.addEventListener("click", (e) => {
            localStorage.setItem("qrcode", true)
            let secondsPassed = 0;
            const secondsLimit = 20;
            document.querySelector("div.qrcode h1").innerHTML = `Refreshes in ${secondsLimit - secondsPassed} seconds`;
            document.querySelector("div.qrcode").style.display = "flex";

            interval = setInterval(() => {
                secondsPassed++;
                if (secondsPassed >= secondsLimit) {
                    window.location.reload()
                } else {
                    document.querySelector("div.qrcode h1").innerHTML = `Refreshes in ${secondsLimit - secondsPassed} seconds`;
                }
            }, 1000);
        });

        closeButton = document.querySelector("div.qrcode button");
        closeButton.addEventListener("click", () => {
            clearInterval(interval)
            document.querySelector("div.qrcode").style.display = "none";
            localStorage.setItem("qrcode", false)
        })
        new QRCode(document.querySelector(".qrcode>.inner"), {
            text: "{% if DEBUG %}http://localhost:8000{% else %}https://pattendance.pooria.tech{% endif %}{% url 'courses:submit' course.id course.code %}",
            width: 1024,
            height: 1024
        });
    </script>
{% endblock %}

templates/pages/course_view.html
{% extends "layouts/app.html" %}
{% load static %}
{% block content_inner %}
    <div class="course-view">
        <div class="left">
            <div class="class {% if attendance %}signed-in{% endif %}"
                 data-targeturl="{% url 'courses:course_view' course.id %}">
                <div class="top">
                    <div class="left">
                        <div class="logo">
                            <h1>{{ course.title.0|capfirst }}</h1>
                        </div>
                        <h1>{{ course.title|capfirst }}</h1>
                    </div>
                </div>
                <div class="bottom">
                    <div class="left">
                        <h3>{{ course.teacher.first_name }} {{ course.teacher.last_name }}</h3>
                    </div>
                    <div class="right">
                        <p>{{ course.start_time|time:"H:i" }}</p>
                        <p>until</p>
                        <p>{{ course.end_time|time:"H:i" }}</p>
                    </div>
                </div>
            </div>
            {% if not attendance %}
                {% if error %}
                    <h2 class="error">{{ details }}</h2>
                {% endif %}
                <h2 class="details">Please scan the QR code provided by your teacher to continue</h2>
            {% endif %}
        </div>
        <div class="right">
            {% if attendance %}
                <div>
                    <h1>You're all set!</h1>
                    <p>You submitted your attendance at {{ attendance.timestamp }}</p>
                    <a href="{% url 'courses:all' %}">Home</a>
                </div>
            {% else %}
                <video></video>
            {% endif %}
        </div>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="code" id="code">
        </form>
    </div>
{% endblock %}

{% if not attendance %}
    {% block custom_javascript %}
        <script>
            const video = document.querySelector("video")
            const input = document.getElementById("code");
            const form = document.querySelector("form")
            let inProgress = false;
            const onResult = (result) => {
                if (inProgress) return;
                input.value = result.data.split("/").pop();
                inProgress = true;
                form.submit()
            }
            const qrScanner = new QrScanner(video, onResult, {
                highlightScanRegion: true,
                disallowCanvasResizing: false,
                alsoTryWithoutScanRegion: true
            });
            qrScanner.setCamera("environment"); // async
            qrScanner.start();
        </script>
    {% endblock %}
{% endif %}

templates/pages/courses_all.html
{% extends 'layouts/app.html' %}

{% block content_inner %}
    <div class="todays-classes">
        <h1>Today's Classes</h1>
        <div class="classes">
            {% if not not_submitted_courses|length and not submitted_courses|length %}
                <h2>There are currently no classes.</h2>
            {% endif %}
            {% for course in submitted_courses %}
                <a class="class active"
                   href="{% url 'courses:course_view' course.id %}"
                >
                    <div class="logo_wrapper">
                        <div class="logo">
                            <h1>{{ course.title.0|capfirst }}</h1>
                        </div>
                        <h1>{{ course.title|capfirst }}</h1>
                    </div>
                    <p>{{ course.start_time|time:"H:i" }}</p>
                </a>
            {% endfor %}
            {% for course in not_submitted_courses %}
                <a class="class"
                   href="{% url 'courses:course_view' course.id %}"
                >
                    <div class="logo_wrapper">
                        <div class="logo">
                            <h1>{{ course.title.0|capfirst }}</h1>
                        </div>
                        <h1>{{ course.title|capfirst }}</h1>
                    </div>
                    <p>{{ course.start_time|time:"H:i" }}</p>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/courses_all_manage.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content_inner %}
    <div class="todays-classes">
        <h1>Classes</h1>
        <div class="classes">
            {% if not courses|length %}
                <h2>No classes are available right now.</h2>
            {% endif %}
            {% for course in courses %}
                <a class="class" href="{% url 'courses:edit' course.id %}">
                    <div class="logo_wrapper">
                        <div class="logo">
                            <h1>{{ course.title.0|capfirst }}</h1>
                        </div>
                        <h1>{{ course.title|capfirst }}</h1>
                    </div>
                    <div class="right">
                        <img src="{% static 'images/edit.svg' %}" alt="">
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/home.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
    <div class="landing">
        <form method="POST" action="{% url 'users:google_landing' %}">
            {% csrf_token %}
            <h1>Pattendance</h1>
            <h2>There's no time like the<br/>PRESENT<br/>
                <p style="font-size: 18px">Made by <a
                        style="color: #3D77BB; text-decoration: none"
                        href="https://pooria.tech">Pooria
                    Ahmadi</a></p></h2>
            <img src="{% static 'images/guy.svg' %}" alt="the_guy">
            <h3>LOGIN TO YOUR ACCOUNT</h3>
            <input type="submit" value="LOGIN USING SCHOOL ACCOUNT">
        </form>
        <div class="showcase">
            <div>
                <h1>There is no time like the</h1>
                <h1>PRESENT</h1>
                <p>Made by <a style="text-decoration: underline; color: white; font-weight: bold"
                              href="https://pooria.tech">Pooria
                    Ahmadi</a></p>
            </div>
        </div>
    </div>
{% endblock %}