courses/urls.py
from django.urls import path
from .views import *

app_name = "courses"

urlpatterns = [
    path("all", All.as_view(), name="all"),
    path("all/manage", AllAdmin.as_view(), name="all_manage"),
    path("<int:id>/view", CourseView.as_view(), name="course_view"),
    path("<int:id>/edit", Edit.as_view(), name="edit"),
    path("<int:id>/delete", Delete.as_view(), name="delete"),
    path("<int:id>/submit/<str:code>", Submit.as_view(), name="submit")
]

main/urls.py
from django.urls import path
from .views import Home


app_name = "main"

urlpatterns = [
    path("", Home.as_view(), name="home")
]

pattendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", "main")),
    path('users/', include("users.urls", "users")),
    path('courses/', include("courses.urls", "courses"))
]

templates/layouts/app.html
<!doctype html>
<html lang="en">
{% include "layouts/head.html" %}
<body>
{% block content %}
    {% include "layouts/header.html" %}
    {% block content_inner %}
    {% endblock %}
{% endblock %}
</body>
{% include "layouts/scripts.html" %}
{% block custom_javascript %}
{% endblock %}
</html>

templates/layouts/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{ WEBSITE_NAME }} - {{ website_title }}</title>
    <meta name="google-signin-client_id"
          content="154280617493-rgn5mgluofrr9ea18l2iunavner30a40.apps.googleusercontent.com">
    <meta name="author" content="Pooria Ahmadi">
    {#     Regular meta tags #}
    <meta name="title" content="{{ website_title }}">
    <meta name="description"
          content="There's no time like the PRESENT">
    {#     Facebook and Google meta tags #}
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://pattendance.pooria.tech/">
    <meta property="og:title" content="{{ website_title }}">
    <meta property="og:description"
          content="There's no time like the PRESENT">
    <meta property="og:image"
          content="https://pattendance.pooria.tech{% static 'images/guy.svg' %}">
    {#     Twitter #}
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://pattendance.pooria.tech/">
    <meta property="twitter:title" content="{{ website_title }}">
    <meta property="twitter:description"
          content="There's no time like the PRESENT">
    {% block custom_meta %}
    {% endblock %}
</head>

templates/layouts/header.html
{% load static %}

<header>
    <div class="left">
        <div class="links">
            <a href="{% url 'main:home' %}">
                <img src="{% static 'images/home.svg' %}" class="home" alt="">
            </a>
            {% if request.user.is_staff %}
                <a href="{% url 'courses:all_manage' %}">
                    <img src="{% static 'images/admin.png' %}" class="admin" alt="">
                </a>
            {% endif %}
        </div>
        <h1>Pattendance</h1>
    </div>
    <div class="right">
        <div class="left"><img
                src="

                        {% if request.user.avatar %}{{ request.user.avatar }}{% else %}{% static 'images/guest.jpg' %}{% endif %}"
                alt=""></div>
        <div class="right">
            <h2>{{ request.user.first_name }} {{ request.user.last_name }}</h2>
            <h3>{{ request.user.email }}</h3>
        </div>
    </div>
</header>

templates/layouts/scripts.html
{% load static %}

<script src="{% static 'js/core.js' %}"></script>
<script src="{% static 'js/qr-scanner-umd.min.js' %}"></script>
<script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>